# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d3b948e78fa22f70642b656ed80ae304b01ed06f77b4fdb16ba912a1583af6260baefab17955c47499644e5a29ddd417d220f8ac5c8d5be4c21e02f6767c2833

test:
  secret_key_base: d0be2b67fbfcd36aa974950e27aeab2d7071e028d8749ccecbea2b8e7be810ba8c03d3d917b24c45c5ae9cc1b19299db920313f440d8ba9b6d2a430cf9f84aea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
